spring.application.name = ezclouds

server.port = 41285
#server.ssl.key-store-type = ${CERT_TYPE}
#server.ssl.key-store = ${CERT_PATH}
#server.ssl.key-store-password = ${CERT_PASS_PHRASE}
#server.ssl.key-alias = ezclouds

#logging.level.org.eclipse.jetty=DEBUG
server.jetty.accesslog.enabled=true

# database setup
spring.datasource.url=jdbc:mysql://localhost:3306/ezservice_election
spring.datasource.username=root
spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect