spring.application.name = ezclouds

server.port = 41285
#server.ssl.key-store-type = ${CERT_TYPE}
#server.ssl.key-store = ${CERT_PATH}
#server.ssl.key-store-password = ${CERT_PASS_PHRASE}
#server.ssl.key-alias = baeldung

#logging.level.org.eclipse.jetty=DEBUG
server.jetty.accesslog.enabled=true