spring.application.name = ezclouds

server.port = ${EZCONF_SERVER_PORT}
#server.ssl.key-store-type = ${CERT_TYPE}
#server.ssl.key-store = ${CERT_PATH}
#server.ssl.key-store-password = ${CERT_PASS_PHRASE}
#server.ssl.key-alias = ezclouds

#logging.level.org.eclipse.jetty=DEBUG
server.jetty.accesslog.enabled=true

# database setup
spring.datasource.url=jdbc:mysql://${EZCONF_DATABASE_HOST}:${EZCONF_DATABASE_PORT}/${EZCONF_DATABASE_NAME}
spring.datasource.username=${EZCONF_DATABASE_USER}
spring.datasource.password=${EZCONF_DATABASE_PASS}
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect

#spring.jpa.properties.hibernate.show_sql=true
#logging.level.org.hibernate.type.descriptor.sql=trace