<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>ezclouds-parent</artifactId>
        <groupId>id.ezclouds</groupId>
        <version>1.0.0</version>
        <relativePath>../../../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <groupId>id.ezclouds.core</groupId>
    <artifactId>ezclouds-core-integration</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>

        <dependency>
            <groupId>id.ezclouds.common</groupId>
            <artifactId>ezclouds-common-util</artifactId>
            <version>1.0.0</version>
        </dependency>

        <dependency>
            <groupId>id.ezclouds.core</groupId>
            <artifactId>ezclouds-core-shared</artifactId>
            <version>1.0.0</version>
        </dependency>
    </dependencies>
</project>