/**
 * Ezclouds.id
 * Copyright (c) 2020‐2024 All Rights Reserved.
 */
package id.ezclouds.core.bifrost.app.web.event;

import id.ezclouds.common.util.context.EzAppEvent;

/**
 * @author Heri Wijoyo (heri.wijoyo@gmail.com)
 * @version $Id: WebEvent.java, v 0.1 2024‐02‐04 11:05 PM Heri Wijoyo (heri.wijoyo@gmail.com) Exp $$
 */
public enum WebEvent implements EzAppEvent {

    GET_IMAGE_PUBLIC("GET_IMAGE_PUBLIC"),
    GET_IMAGE_PRIVATE("GET_IMAGE_PRIVATE"),

    WEB_LOGIN_BY_SESSION_CODE("WEB_LOGIN_BY_SESSION_CODE"),
    WEB_VALIDATE_SESSION_ID("WEB_VALIDATE_SESSION_ID"),
    WEB_PAGE_ORG_DOWNLOAD("WEB_PAGE_ORG_DOWNLOAD"),
    WEB_DOWNLOAD_APK("WEB_DOWNLOAD_APK"),
    WEB_PAGE_ADMIN_CONFIG("WEB_PAGE_ADMIN_CONFIG"),
    WEB_PAGE_ADMIN_ADD_MEMBER("WEB_PAGE_ADMIN_ADD_MEMBER"),
    WEB_PAGE_ADMIN_SPECIAL_PROCESS("WEB_PAGE_ADMIN_SPECIAL_PROCESS"),
    WEB_PAGE_ADMIN_PUBLIC_REPORT("WEB_PAGE_ADMIN_PUBLIC_REPORT"),
    WEB_PAGE_ADMIN_PUBLIC_DATA_APP("WEB_PAGE_ADMIN_PUBLIC_DATA_APP"),

    WEB_API_GET_APP_DATA("WEB_API_GET_APP_DATA"),
    WEB_API_GET_DASHBOARD("WEB_API_GET_DASHBOARD"),
    WEB_API_GET_IMAGE_GALLERY("WEB_API_GET_IMAGE_GALLERY"),
    WEB_API_UPDATE_IMAGE_GALLERY("WEB_API_UPDATE_IMAGE_GALLERY"),
    WEB_API_NEWS_GET("WEB_API_NEWS_GET"),
    WEB_API_NEWS_DETAIL("WEB_API_NEWS_DETAIL"),
    WEB_API_NEWS_FLAG_SWITCH("WEB_API_NEWS_FLAG_SWITCH"),
    WEB_API_EVENT_GET("WEB_API_EVENT_GET"),
    WEB_API_EVENT_DETAIL("WEB_API_EVENT_DETAIL"),
    WEB_API_EVENT_FLAG_SWITCH("WEB_API_EVENT_FLAG_SWITCH"),
    WEB_API_VIDEO_CARD_GET("WEB_API_VIDEO_CARD_GET"),
    WEB_API_VIDEO_CARD_UPDATE("WEB_API_VIDEO_CARD_UPDATE"),
    WEB_API_PROFILE_DETAIL("WEB_API_PROFILE_DETAIL"),
    WEB_API_PROFILE_UPDATE("WEB_API_PROFILE_UPDATE"),
    WEB_API_PROFILE_UPDATE_BIO("WEB_API_PROFILE_UPDATE_BIO"),
    WEB_API_WHATSAPP_LOG("WEB_API_WHATSAPP_LOG"),
    WEB_API_RESEND_WHATSAPP("WEB_API_RESEND_WHATSAPP"),
    WEB_API_GET_APP_DOCUMENTS("WEB_API_GET_APP_DOCUMENTS"),
    WEB_API_GET_SUB_ORGANIZATIONS("WEB_API_GET_SUB_ORGANIZATIONS"),
    WEB_API_GET_SUB_ORGANIZATION_ALL("WEB_API_GET_SUB_ORGANIZATION_ALL"),
    WEB_API_CREATE_SUB_ORGANIZATION("WEB_API_CREATE_SUB_ORGANIZATION"),
    WEB_API_GET_MEMBERS("WEB_API_GET_MEMBERS"),
    WEB_API_GET_MEMBER_DETAIL("WEB_API_GET_MEMBER_DETAIL"),
    WEB_API_MEMBER_UPDATE_ROLES("WEB_API_MEMBER_UPDATE_ROLES"),
    WEB_API_CREATE_MEMBER("WEB_API_CREATE_MEMBER"),
    WEB_API_IMPORT_MEMBER_CSV("WEB_API_IMPORT_MEMBER_CSV"),

    WEB_API_COMMON_SWITCH_FLAG("WEB_API_COMMON_SWITCH_FLAG"),
    ADMIN_COMMON_POST_WITH_FILE_UPLOAD("ADMIN_COMMON_POST_WITH_FILE_UPLOAD"),

    //super admin
    WEB_API_GET_ORGANIZATION("WEB_API_GET_ORGANIZATION"),
    WEB_API_GET_ORGANIZATION_DETAIL("WEB_API_GET_ORGANIZATION_DETAIL"),
    WEB_API_CREATE_ORGANIZATION("WEB_API_CREATE_ORGANIZATION"),
    WEB_API_UPDATE_ORGANIZATION("WEB_API_UPDATE_ORGANIZATION"),
    WEB_API_GET_APP_CONFIG("WEB_API_GET_APP_CONFIG"),
    WEB_API_UPDATE_CLIENT_APP_CONFIG("WEB_API_UPDATE_CLIENT_APP_CONFIG"),
    WEB_API_UPDATE_APP_CONFIG("WEB_API_UPDATE_APP_CONFIG"),
    WEB_API_UPDATE_CORE_ORG_CONFIG("WEB_API_UPDATE_CORE_ORG_CONFIG"),
    WEB_API_CREATE_ADMIN_ORG("WEB_API_CREATE_ADMIN_ORG"),
    WEB_API_WHATSAPP_SEND("WEB_API_WHATSAPP_SEND"),
    WEB_API_REFRESH_ALL_CACHES("WEB_API_REFRESH_ALL_CACHES"),
    WEB_API_REFRESH_ALL_DIRECTORIES("WEB_API_REFRESH_ALL_DIRECTORIES"),
    WEB_API_REFRESH_ALL_MENUS("WEB_API_REFRESH_ALL_MENUS"),
    WEB_API_COMMON_IMPORT("WEB_API_COMMON_IMPORT"),
    WEB_API_RELOAD_REPORT("WEB_API_RELOAD_REPORT"),
    WEB_API_MEMBER_REQUIRED_DATA("WEB_API_MEMBER_REQUIRED_DATA"),
    WEB_API_CORE_AREA("WEB_API_CORE_AREA"),

    WEB_API_BIZ_COMMON_TABLES("WEB_API_BIZ_COMMON_TABLES"),
    WEB_API_BIZ_COMMON_TABLE_CREATE("WEB_API_BIZ_COMMON_TABLE_CREATE"),
    WEB_API_BIZ_COMMON_TABLE_DETAIL("WEB_API_BIZ_COMMON_TABLE_DETAIL"),
    WEB_API_BIZ_COMMON_TABLE_UPDATE("WEB_API_BIZ_COMMON_TABLE_UPDATE"),

    ;

    private final String code;

    WebEvent(String code) {
        this.code = code;
    }

    @Override
    public String getEventCode() {
        return this.code;
    }
}